# 45. 프로미스

문제
데이터를 가져올 때 지정한 시간 내에 데이터를 받지 못하면 timeOut으로 처리하기 위해 아래의 코드의 빈칸에 들어가야하는 프로미스 정적 메서드는?
```javascript
function fetchDataWithTimeout(url, timeout) {
  const fetchDataPromise = fetch(url); // 데이터 가져오기 프라미스
  const timeoutPromise = new Promise((resolve, reject) => {
    setTimeout(() => {
      reject(new Error('Request Timed Out'));
    }, timeout);
  });

  return Promise._____([fetchDataPromise, timeoutPromise]);
}

const apiUrl = 'https://jsonplaceholder.typicode.com/posts/1'; // 예시 URL
const requestTimeout = 3000; // 3초 타임아웃

fetchDataWithTimeout(apiUrl, requestTimeout)
  .then((response) => {
    if (response.ok) {
      return response.json();
    } else {
      throw new Error('Network response was not ok.');
    }
  })
  .then((data) => {
    console.log(data);
  })
  .catch((error) => {
    console.error(error.message); // 타임아웃 또는 다른 에러 메시지 출력
  });
```


## 개요

### 자바스크립트는 비동기 처리를 위한 하나의 패턴으로 콜백함수를 사용한다. 

- 전통적인 콜백함수의 단점
  - 콜백 헬로 인해 가독성이 나쁘다. 
  - 비동기 처리 중 발생한 처리가 곤란해서 여러개의 비동기 처리를 한번에 하기 어렵다.
- 프로미스
  - ES6에서 도입
  - 비동기 처리를 위한 패턴
  - 전통적인 콜백 패턴이 가진 단점을 보완
  - 비동기 처리 시점을 명ㅓ확하게 표현할 수 있다. 

## 1. 전통적인 콜백 패턴의 단점

### 1. 콜백 헬

- 비동기 함수 내부의 비동기로 동작하는 코드에서 ''처리 결과를 외부로 반환''하거나 ''상위 스코프의 변수에 할당''하면 **기대한 대로 동작하지 않는다.**

  - 비동기 함수란

    - 비동기함수 : 함수 내부에 비동기로 동작하는 코드를 포함한 함수
    - 비동기 함수를 호출하면 함수 내부의 비동기로 동작하는 코드가 완료되지 않았다 해도 기다리지 않고 즉시 종료된다.
    - 즉, 비동기 함수 내부의 비동기로 동작하는 코드는 비동기 함수가 종료된 이후에 완료된다.

  - 예를 들어

    setTimeout 함수를 호출하면 콜백 함수를 호출 스케줄링한 다음, 타이머 id를 반환하고 즉시 종료된다.   
    즉, 비동기 함수인 setTimeout 함수의 <span style="color:red">콜백 함수</span>는 setTimeout 함수가 종료된 이후에 호출된다.   
    따라서 setTimeout 함수 내부의 콜백 함수에서 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하면 기대한 대로 동작하지 않는다.

    ```javascript
    let g = 0;  
    // 비동기 함수인 setTimeout 함수는 콜백 함수의 처리 결과를 외부로 반환하거나 상위 스코프의 변수에 할당하지 못한다.  
    setTimeout(() => { g = 100; } , 0);  
    console . log(g); // 0
    ```

  - GET 요청을 전송하고 서버의 응답을 전달받는 get 함수도 비동기 함수다.

    - get 함수가 비동기 함수인 이유는 get 함수 내부의 onload 이벤트 핸들러가 비동기로 동작하기 때문이다.
    - get 함수를 호출하면 GET 요청을 전송하고 onload 이벤트 핸들러를 등록한 다음 undefined 를 반환하고 즉시 종료된다.
    - 즉, 비동기 함수인 get  함수 내부의 onload 이벤트 핸들러는 get 함수가 종료된 이후에 실행된다.

- get 함수의 onload 이벤트 핸들러에서 서버의 응답 결과를 반환하거나 상위 스코프의 변수에 할당하면 **기대한 대로 동작하지 않는다.**

  - 1. onload 이벤트 헨들러의 반환값을 취득하기

    - 1. get 함수가 호출되면 XMLHttpRequest 객체를 생성하고, HTTP 요청을 초기화한 후, HTTP 요청을 전송한다.

    - 2. xhr.onload 이벤트 핸들러 프로퍼티에 이벤트 핸들러를 바인딩하고 종료한다.

    - 3. 이때 get 함수에 명시적인 반환문이 없으므로 get 함수는 undefined 를 반환한다.

      - xhr.onload 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러의 반환문은 get 함수의 반환문이 아니다.
      - onload 이벤트 핸들러는 get 함수가 호출하지 않기 때문에 onload 이벤트 핸들러의 반환값은 캐치할 수 없다.
        - 비동기 프로그래밍
          - 콜백 함수를 태스크 큐에 푸시하는 것은 브라우저의 역할이다.
          - 콜백 함수가 태스크 큐에 푸시되어 대기한 후 콜 스택이 비어야 호출된다. 
        - 이벤트 핸들러의 반환값은 의미가 없다. 

  - 2. onload 이벤트 내의 서버 응답 결과를 상위 스코프의 변수에 할당하기

    - 1. 비동기 함수 get 이 호출되면 함수 코드를 평가하는 과정에서 get 함수의 실행 컨텍스트가 생성되고 실행 컨텍스트 스택(콜 스택)에 푸시된다.
    - 2. 이후 함수 코드 실행 과정에서 `xhr.onload` 이벤트 핸들러 프로퍼티에 이벤트 핸들러가 바인딩된다.
    - 3. get 함수가 종료하면 get 함수의 실행 컨텍스트가 콜 스택에서 팝되고, 곧바로 `console.log` 가 호출된다.
    - 4. 이때 `console.log` 의 실행 컨텍스트가 생성되어 실행 컨텍스트 스택에 푸시된다.
    - 만약 `console.log` 가 호출되기 직전에 load 이벤트가 발생했더라도 `xhr.onload` 이벤트 핸들러 프로퍼티에 바인딩한 이벤트 핸들러는 결코 `console.log` 보다 먼저 실행되지 않는다.
      - `xhr.onload` 이벤트 핸들러는 load 이벤트가 발생하면 일단 태스크 큐에 저장되어 대기하다가, 콜 스택이 비면 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다.
      - 이벤트 핸들러도 함수이므로 이벤트 핸들러의 평가 → 이벤트 핸들러의 실행 컨텍스트 생성 → 콜 스택에 푸시 → 이벤트 핸들러 실행 과정을 거친다.
      - 따라서 `xhr.onload` 이벤트 핸들러가 실행되는 시점에는 콜 스택이 빈 상태여야 하므로 `console.log` 는 이미 종료된 이후다.
      - 만약 get 함수 이후에 `console.log` 가 100번 호출된다 해도 xhr.onload 이벤트 핸들러는 모든 `console.log`가 종료한 이후에 실행된다.
      - 즉, `xhr.onload` 이벤트 핸들러에서 상위 스코프의 변수에 서버의 응답 결과를 할당하기 이전에 `console.log` 가 먼저 호출되어 undefined 가 출력된다.

  - 이처럼 비동기 함수는 비동기 처리 결과를 외부에 반환할 수 없고, 상위 스코프의 변수에 할당할 수도 없다.

- ❗️따라서 비동기 함수의 처리 결과(서버의 응답 등)에 대한 후속 처리는 **비동기 함수 내부에서 수행해야 한다.**

  - 이때 비동기 함수를 범용적으로 사용하기 위해 비동기 함수에 비동기 처리 결과에 대한 후속 처리를 수행하는 콜백 함수를 전달하는 것이 일반적이다.

    - 필요에 따라 비동기 처리가 성공하면 호출될 콜백 함수(successCallback)와 비동기 처리가 실패하면 호출될 콜백 함수(failureCallback)를 전달할 수 있다.

    - ```javascript
      // GET 요청을 위한 비동기 함수  
      const get = (url , successCallback , failureCallback) => {   
      	const xhr = new XMLHttpRequest();  
      	xhr.open('GET' , url);  
      	xhr.send();  
      	xhr.onload = () => {   
      	if (xhr.status === 200) {  
      		// 서버의 응답을 콜백 함수에 인수로 전달하면서 호출하여 응답에 대한 후속 처리를 한다.  
      		successCallback(JSON.parse(xhr.response));  
      		} else {  
      		// 에러 정보를 콜백 함수에 인수로 전달하면서 호출하여 에러 처리를 한다.  
      		failureCallback(xhr.status);  
      		}   
      	};  
      };  
      // id가 1인 post를 취득   
      // 서버의 응답에 대한 후속 처리를 위한 콜백 함수를 비동기 함수인 get에 전달해야 한다.  
      get('https://jsonplaceholder.typicode.com/posts/1', console.log, console.error);  
      /*  
      {  
      "userId": 1,  
      "id": 1,  
      }  
      */
      ```

- 이처럼 '콜백 함수를 통해 비동기 처리 결과에 대한 후속 처리를 수행하는 비동기 함수'가 

- 비동기 처리 결과를 가지고 또다시 비동기 함수를 호출해야 한다면 

- 콜백 함수 호출이 중첩되어 복잡도가 높아지는 현상이 발생하는데, 

- **이를 콜백 헬 callback hell 이라 한다.**

### 2. 에러 처리의 한계

- 콜백 헬보다 심각한 단점
- try 코드 블록 내에서 호출한 setTimeout 함수는 1초 후에 콜백 함수가 실행되도록 타이머를 설정하고, 이후 콜백 함수는 에러를 발생시킨다.
- 하지만 이 에러는 catch 코드 블록에서 캐치되지 않는다.
  ```javascript
  try { setTimeout(() => { throw new Error('Error!'); } , 1000);  
  } catch (e) {  
  // 에러를 캐치하지 못한다  
  console . error('캐치한 에러', e);  
  }
  ```
  - setTimeout의 콜백함수는 setTimeout이 호출하는 것이 아니다. 
    - setTimeout의 콜백함수가 호출되는 과정
      - 비동기 함수인 setTimeout 이 호출되면 setTimeout 함수의 실행 컨텍스트가 생성되어 콜 스택에 푸시되어 실행된다.
      - setTimeout 은 비동기 함수이므로 콜백 함수가 호출되는 것을 기다리지 않고 즉시 종료되어 콜 스택 에서 제거된다.
      - 이후 타이머가 만료되면 setTimeout 함수의 콜백 함수는 태스크 큐로 푸시되고 콜 스택이 비어졌을 때 이벤트 루프에 의해 콜 스택으로 푸시되어 실행된다. 
  - setTimeout의 콜백함수가 실행될 때의 상황
    - setTimeout 함수의 콜백 함수가 실행될 때 setTimeout 함수는 이미 콜 스택에서 제거된 상태다.
      - setTimeout 함수의 콜백 함수의 호출자가 setTimeout 함수라면 콜 스택의 현재 실행 중인 실행 컨텍스트가 콜백 함수의 실행 컨텍스트일 때 현재 실행 중인 실행 컨텍스트의 하위 실행 컨텍스트가 setTimeout 함수여야 한다.
  - 에러의 전파
    - 에러는 호출자 방향으로 전파된다. 즉, 콜 스택의 아래 방향(실행 중인 실행 컨텍스트가 푸시되기 푸시되기 직전에 푸시된 실행 컨텍스트 방향)으로 전파된다.
    - 따라서 setTimeout 함수의 콜백 함수가 발생시킨 에러는 catch 블록에서 캐치되지 않는다.

#### 이를 극복하기 위해 ES6에서 프로미스 Promise 가 도입되었다.

## 2. 프로미스의 생성

 ```javascript
const promise = new Promise((resolve , reject) => {  
  // Promise 함수의 콜백 함수 내부에서 비동기 처리를 수행한다.  
  if (/* 비동기 처리 성공 */) { 
  	resolve('result');  
  } else { 
  	/* 비동기 처리 실패 */ 
  	reject('failure reason');  
  } 
});
 ```



### new 연산자 + Promise 생성자 함수 호출

### Promise 는 호스트 객체가 아닌 ECMAScript 사양에 정의된 표준 빌트인 객체다.

### resolve와 reject함수를 인수로 전달받는다. 

- ECMAScript 사양에서는 executor 함수라고 부른다
- Promise 생성자 함수는 비동기 처리를 수행할 콜백 함수
  - resolve 함수 : 비동기 처리 성공
  - reject 함수 : 비동기 처리 실패
- 예시
```javascript
   // GET 요청을 위한 비동기 함수
  const promiseGet = (url) => {
    return new Promise((resolve, reject) => {
      const xhr = new XMLHttpRequest();
      xhr.open("GET", url);
      xhr.send();
      xhr.onload = () => {
        if (xhr.status === 200) {
          // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.
          resolve(JSON.parse(xhr.response));
        } else {
          // 에러 처리를 위해 reject 함수를 호출한다.
          reject(new Error(xhr.status));
        }
      };
    });
  };
  // promiseGet 함수는 프로미스를 반환한다.
  promiseGet("https://jsonplaceholder . typicode . com/posts/1");
  ```
	- 비동기 함수인 promiseGet 은 함수 내부에서 프로미스를 생성하고 반환한다.
	- 비동기 처리는 Promise 생성자 함수가 인수로 전달받은 콜백 함수 내부에서 수행한다.
	- 만약 비동기 처리가 성공하면 비동기 처리 결과를 resolve 함수에 인수로 전달하면서 호출하고, 비동기 처리가 실패하면 에러를 reject 함수에 인수로 전달하면서 호출한다.

### 프로미스는 비동기 처리 상태와 처리 결과를 관리하는 객체다.
- 프로미스의 상태 정보
	- 프로미스의 상태는 resolve 또는 reject 함수를 호출하는 것으로 결정된다.
	- 1. pending
		- 프로미스가 생성된 직후 기본 상태
	- 2. settled
		- pending이 아닌 상태
		- 다시 pending으로 돌아갈 수 없다. 
		- 2-1. fulfilled
			- 비동기 처리 성공: resolve 함수를 호출해 프로미스를 fulfilled 상태로 변경한다.
		- 2-2. rejected
			- 비동기 처리 실패: reject 함수를 호출해 프로미스를 rejected 상태로 변경한다.
- 프로미스의 결과 정보
	- fulfilled 상태의 경우
		- 비동기 처리 결과를 값으로 갖는다
	- rejected 상태의 경우
		- Error객체를 값으로 갖는다. 

## 3. 프로미스의 후속 처리 메서드

### 프로미스는 후속 메서드 then, catch, finally 를 제공한다.
- 후속 처리 메서드의 콜백 함수에 프로미스의 처리 결과가 인수로 전달된다.
	- 모든 후속 처리 메서드는 프로미스를 반환하며, 비동기로 동작한다.

### 1. Promise.prototype.then
- 인수
	- 두 개의 콜백 함수를 인수로 전달받는다.
	- 1. 비동기 처리가 성공했을 때 호출되는 성공 처리 콜백 함수
		```javascript
      new Promise((**resolve**) => resolve("fulfilled")).then(  
		    (v) => console.log(v),  
		    (e) => console.error(e)  
		  ); // fulfilled*
      ```
		- 프로미스가 fulfilled 상태(resolve 함수가 호출된 상태)가 되면 호출된다.
		- 이때 콜백 함수는 프로미스의 비동기 처리 결과를 인수로 전달받는다.
	- 2. 비동기 처리가 실패했을 때 호출되는 실패 처리 콜백 함수
		```javascript
      new Promise((_, **reject**) => reject(new Error("rejected"))).then(  
		    (v) => console.log(v),  
		    (e) => console.error(e)  
		  ); *// Error: rejected*
      ```
		- 프로미스가 rejected 상태(reject 함수가 호출된 상태)가 되면 호출된다.
		- 이때 콜백 함수는 프로미스의 에러를 인수로 전달받는다.
- 반환
	- 언제나 프로미스를 반환한다.
	- then 메서드의 콜백 함수가 프로미스를 반환하면 그 프로미스를 그대로 반환
	- 콜백 함수가 프로미스가 아닌 값을 반환하면 그 값을 암묵적으로 resolve 또는 reject 하여 프로미스를 생성해 반환한다.

### 2 Promise.prototype.catch
- 인수
	- 한 개의 콜백 함수를 인수로 전달받는다.
	- catch 메서드의 콜백 함수는 프로미스가 rejected 상태인 경우만 호출된다.
	```javascript
      	new Promise((_, reject) => reject(new Error("rejected"))).catch((e) =>  
		console.log(e)  
	); *// Error: rejected*
    	```
- catch 메서드는 then(undefined , onRejected) 과 동일하게 동작한다.
  ```javascript
  new Promise((_, reject) => reject(new Error("rejected"))).then(undefined, (e) =>
  	console.log(e)
  ); *// Error: rejected*
  ```
- 따라서 then 메서드와 마찬가지로 언제나 프로미스를 반환한다.

### 3. Promise.prototype.finally
- 한 개의 콜백 함수를 인수로 전달받는다.
- finally 메서드의 콜백 함수는 프로미스의 성공(fulfilled) 또는 실패(rejected)와 상관없이 무조건 한 번 호출된다.
	```javascript
   new Promise(() => {}).finally(() => console.log("finally")); *// finally*
  ```
- finally 메서드는 프로미스의 상태와 상관없이 공통적으로 수행해야 할 처리 내용이 있을 때 유용하다.
- finally 메서드도 then/catch 메서드와 마찬가지로 언제나 프로미스를 반환한다.
- 예제
	```javascript
		const promiseGet = (url) => {  
		  return new Promise((resolve, reject) => {  
		    const xhr = new XMLHttpRequest();  
		    xhr.open("GET", url);  
		    xhr.send();  
		    xhr.onload = () => {  
		      if (xhr.status === 200) {  
		        // 성공적으로 응답을 전달받으면 resolve 함수를 호출한다.  
		        resolve(JSON.parse(xhr.response));  
		      } else {  
		        // 에러 처리를 위해 reject 함수를 호출한다.  
		        reject(new Error(xhr.status));  
		      }  
		    };  
		  });  
		};  
		// promiseGet 함수는 프로미스를 반환한다.  
		promiseGet("https://jsonplaceholder . typicode . com/posts/1")  
		  .then((res) => console.log(res))  
		  .catch((err) => console.error(err))  
		  .finally(() => console.log("Bye!"));
    ```

 ## 4. 프로미스의 에러 처리

### 비동기 처리를 위한 콜백 패턴과 달리, 프로미스는 에러를 문제없이 처리할 수 있다.

### 비동기 처리에서 발생한 에러는 then 메서드의 두 번째 콜백 함수 또는 catch 메서드로 처리할 수 있다.
```javascript
   const wrongUrl = "https://jsonplaceholder . typicode . com/XXX/1";
  // 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
  promiseGet(wrongUrl).then(
    (res) => console.log(res),
    (err) => console.error(err)
  ); // Error: 404

  const wrongUrl = "https://jsonplaceholder . typicode . com/XXX/1";
  // 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
  promiseGet(wrongUrl)
    .then((res) => console.log(res))
    .catch((err) => console.error(err)); // Error: 404

  const wrongUrl = "https://jsonplaceholder . typicode . com/XXX/1";
  // 부적절한 URL이 지정되었기 때문에 에러가 발생한다.
  promiseGet(wrongUrl)
    .then((res) => console.log(res))
    .catch((err) => console.error(err)); // Error: 404
```
- 위 세개의 예시는 모두 같은 동작을 한다.

### catch 메서드를 모든 then 메서드를 호출한 이후에 호출하면 비동기 처리에서 발생한 에러( rejected 상태) 뿐만 아니라 then 메서드 내부에서 발생한 에러까지 모두 캐치할 수 있다.
- Then 내부에서 두번째 콜백함수는 첫번째 콜백함수의 에러를 캐치할 수 없다.
  ```javascript
     promiseGet("https://jsonplaceholder . typicode . com/todos/1")
    .then((res) => console.xxx(res))
    .catch((err) => console.error(err)); // TypeError: console.xxx is not a function
   ```


## 5. 프로미스 체이닝

### 비동기 처리를 위한 콜백 패턴의 ‘콜백 헬’ 문제를 해결할 수 있다.
```javascript
   const url = "https://jsonplaceholder . typicode . com";
  // id가 1인 post의 userId를 취득
  promiseGet(`${url}/posts/1`)
    // 취득한 post의 userId로 user 정보를 취득
    .then(({ userId }) => promiseGet(`${url}/users/${userId}`))
    .then((userInfo) => console.log(userInfo))
    .catch((err) => console.error(err));
  ```

### 프로미스는 프로미스 체이닝을 통해 비동기 처리 결과를 전달받아 후속 처리를 하므로 비동기 처리를 위한 콜백 패턴에서 발생하던 콜백 헬이 발생하지 않는다.


## 6. 프로미스의 정적 메서드

### Promise는 주로 생성자 함수로 사용되지만, 함수도 객체이므로 메서드를 가질 수 있다.

### 1. Promise.resolve/Promise.reject
- Promise.resolve와 Promise.reject 메서드는 이미 존재하는 값을 래핑하여 프로미스를 생성하기 위해 사용 한다.
	- 아래 두 예제는 동일하게 동작한다.
	```javascript
 	const resolvedPromise = Promise.resolve([1, 2, 3]);
	resolvedPromise.then(console.log); // [1, 2, 3]
 	```
	```javascript
	const resolvedPromise = new Promise((resolve) => resolve([1, 2, 3]));
	resolvedPromise.then(console.log); // [1, 2, 3]
 	```
	- 아래 두 예제는 동일하게 동작한다.
	```javascript
 	const rejectedPromise = Promise.reject(new Error("Error!"));
	rejectedPromise.catch(console.log); // Error: Error!
	```
 	```javascript
	const rejectedPromise = new Promise((_, reject) => reject(new Error("Error!")));
	rejectedPromise.catch(console.log); // Error: Error!
  	```

### 2. Promise.all
- 여러개의 비동기 처리를 모두 병렬로 처리할 때 사용한다. 
- 순차적으로 처리
	 ```javascript
 	   const res = [];
	  requestData1().then(data => { res.push(data);
	  return requestData2();
	  }).then(data => { res.push(data);
	  return requestData3();
	  })
	  .then(data => { res . push(data);
	  console.log(res); // [1, 2, 3] ⇒ 약 6초 소요 })
	  .catch(console.error);
- 병렬로 처리
	- Promise.all([requestData1(), requestData2(), requestData3()])
	  .then(console.log) // [ 1, 2, 3 ] ⇒ 약 3초 소요
   	  .catch(console.error);
- Promise.all 메서드는 인수로 전달받은 배열의 모든 프로미스가 모두 fulfilled 상태가 되면 종료한다.
	- 전달받은 배열의 프로미스가 하나라도 rejected 상태가 되면 나머지 프로미스가 fulfilled 상태가 되는 것을 기다리지 않고 즉시 종료한다.
- 따라서 Promise.all 메서드가 종료하는 데 걸리는 시간은 가장 늦게 fulfilled 상태가 되는 프로미스의 처리 시간보다 조금 더 길다.
- 첫 번째 프로미스가 가장 나중에 fulfilled 상태가 되어도 Promise.all 메서드는 첫 번째 프로미스가 resolve 한 처리 결과부터 차례대로 배열에 저장해 그 배열을 resolve 하는 새로운 프로미스를 반환한다.
	- 즉, 처리 순서가 보장된다.
- 예제
	```javascript
 	 const githubIds = ['jeresig' , 'ahejlsberg' , 'ungmo2'];
  
	  Promise.all(githubIds . map(id => promiseGet(`https://api . github . com/users/${id}`)))
  
	  // ['jeresig', 'ahejlsberg', 'ungmo2'] => Promise [userInfo, userInfo, userInfo]
  
	  .then(users => users.map(user => user . name))
  
	  // [userInfo, userInfo, userInfo] // => Promise ['John Resig', 'Anders Hejlsberg', 'Ungmo Lee']
  
	  .then(console.log)
	  .catch(console.error);
	```
### 3. Promise.race
- 가장 먼저 fulfilled 상태가 된 프로미스의 처리 결과를 resolve 하는 새로운 프로미스를 반환한다.
- 프로미스가 하나라도 rejected 상태가 되면 에러를 reject 하는 새로운 프로미스를 즉시 반환한다.

### 4. Promise.allSettled
- 전달받은 프로미스가 모두 settled 상태가 되면 처리 결과를 배열로 반환한다.
- IE를 제외한 대부분의 모던 브라우저에서 지원한다.
- ```javascript
  Promise.allSettled([ new Promise(resolve => setTimeout(() => resolve(1), 2000)) ,
  new Promise((_ , reject) => setTimeout(() => reject(new Error('Error!')), 1000)) ]) . then(console.log);
  /*
  [ {status: "fulfilled", value: 1}, {status: "rejected", reason: Error: Error! at <anonymous>:3:54} ]
  */
  ```
- 모든 프로미스의 처리 결과를 반환한다. 
	- fulfilled : status, value
	- rejected : status, reason

## 7. 마이크로 태스크 큐

### 프로미스의 후속 처리 메서드의 콜백 함수는 태스크 큐가 아니라 “**마이크로 태스크 큐”**에 저장된다.

### 마이크로태스크 큐는 태스크 큐와는 별도의 큐다.

### 후속 처리 메서드의 콜백 함수 => 마이크로 태스크 큐에 일시 저장

### 그 외의 비동기 함수의 콜백 함수나 이벤트 핸들러 => 태스크 큐에 일시 저장

### 마이크로태스크 큐는 태스크 큐보다 우선순위가 높다.

### 즉, 이벤트 루프는 콜 스택이 비면 먼저 마이크로태스크 큐에서 대기하고 있는 함수를 가져와 실행한다.

## 8. fetch

### fetch 함수란
- XMLHttpRequest 객체와 마찬가지로 HTTP 요청 전송 기능을 제공하는 클라이언트 사이드 Web API다.
- XMLHttpRequest 객체보다 사용법이 간단하고 프로미스를 지원하기 때문에 비동기 처리를 위한 콜백 패턴의 단점에서 자유롭다.
- 인터넷 익스플로러를 제외한 대부분의 모던 브라우저에서 제공한다.

### 사용 방법
- fetch 함수에는 HTTP 요청을 전송할 URL과 HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체를 전달한다.
- `const promise = fetch(url [ , options])`

### 반환
- HTTP 응답을 나타내는 Response 객체를 래핑한 Promise 객체를 반환한다.

### 예시
- fetch 함수에 첫 번째 인수로 HTTP 요청을 전송할 URL만 전달하면 GET 요청을 전송한다.
  ```javascript
	fetch('https://jsonplaceholder.typicode.com/todos/1').then(response => console.log(response));  
	  
	> Promise {<pending>}  
	[[Prototype]]: Promise  
	[[PromiseState]]: "fulfilled"  
	[[PromiseResult]]: undefined  
	  
	> Response {type: 'cors', url: 'https://jsonplaceholder.typicode.com/todos/1', redirected: false, status: 200, ok: true, …}  
	body: (...)  
	bodyUsed: false  
	headers: Headers {}  
	ok: true  
	redirected: false  
	status: 200  
	statusText: ""  
	type: "cors"  
	url: "https://jsonplaceholder.typicode.com/todos/1"  
	[[Prototype]]: Response
  	```
- Response 객체
	- HTTP 응답을 나타낸다.
	- 후속 처리 메서드then 을 통해 프로미스가 resolve 한 Response 객체를 전달받을 수 있다.
	- Response 객체는 HTTP 응답을 나타내는 다양한 프로퍼티를 제공한다.
- Response.prototype
	- Response 객체에 포함되어 있는 HTTP 응답 몸체를 위한 다양한 메서드를 제공한다.
	- 예를 들어, `Response.prototype.json` 메서드는 Response 객체에서 HTTP 응답 몸체 response.body 를 취득하여 역직렬화한다.

### fetch 함수를 사용할 때는 에러 처리에 주의해야 한다.
- 기본적으로 404 Not Found 나 500 Internal Server Error 와 같은 HTTP 에러가 발생해도 에러를 reject 하지 않고
- 불리언 타입의 ok 상태를 false 로 설정한 Response 객체를 resolve 한다.
- 오프라인 등의 네트워크 장애나 CORS 에러에 의해 요청이 완료되지 못한 경우에만 프로미스를 reject 한다.
- 따라서 fetch 함수를 사용할 때는 다음과 같이 fetch 함수가 반환한 프로미스가 resolve한 불리언 타입의 ok 상태를 확인해 명시적으로 에러를 처리할 필요가 있다.
	```javascript
 	const wrongUrl = "https://jsonplaceholder.typicode.com/XXX/1";

	fetch(wrongUrl)
  	// response는 HTTP 응답을 나타내는 Response 객체다.
  	.then((response) => {
   	 if (!**response.ok**) throw new Error(response.statusText);
   	 return response.json();
  	})
  	.then((todo) => console.log(todo))
  	.catch((err) => console.error(err));
 	```
- 참고
	- axios는 모든 HTTP 에러를 reject하는 프로미스를 반환하여 모든 에러를 catch에서 처리할 수 있어 편리하다.
	- 또한 axios는 인터셉터, 요청 설정 등 fetch 보다 다양한 기능을 지원한다.

### fetch 함수를 통해 HTTP 요청을 전송하기
- 인수
	- 첫 번째 인수 : HTTP 요청을 전송할 URL
	- 두번째 인수 : HTTP 요청 메서드, HTTP 요청 헤더, 페이로드 등을 설정한 객체
- 예제
	```javascript
 	const request = {
  	get(url) {
    	return fetch(url);
  	},

  	post(url, payload) {
    	return fetch(url, {
     	 method: "POST",
      	headers: { "content-Type": "application/json" },
     	 body: JSON.stringify(payload),
    	});
  	},

  	patch(url, payload) {
    	return fetch(url, {
      	method: "PATCH",
      	headers: { "content-Type": "application/json" },
      	body: JSON.stringify(payload),
    	});
  	},

  	delete(url) {
    	return fetch(url, { method: "DELETE" });
  	},
	};
 	```
